name: ci

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build Solution (x64)
      run: msbuild "-p:Configuration=Release;Platform=x64;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln
    - name: Build Solution (ARM64)
      run: msbuild "-p:Configuration=Release;Platform=ARM64;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln
      # Win32 built last
    - name: Build Solution (Win32)
      run: msbuild "-p:Configuration=Release;Platform=Win32;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln

    - name: Upload everything to Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Everything
        path: .\bin\Release\**\*.*
    - name: Upload ThemeTool to Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ThemeTool
        path: |
          .\bin\Release\Win32\ThemeTool.exe
          .\bin\Release\Win32\ThemeTool.pdb
    - name: Create Release
      id: create_release
      uses: comnoco/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
