name: ci

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build Solution (x64)
      run: msbuild "-p:Configuration=Release;Platform=x64;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln
    - name: Build Solution (ARM64)
      run: msbuild "-p:Configuration=Release;Platform=ARM64;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln
    - name: Build Solution (Win32)
      run: msbuild "-p:Configuration=Release;Platform=Win32;CI_VERSION=${{ github.ref_name }}" SecureUxTheme.sln

    - name: Upload everything to Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Everything
        path: .\bin\Release\**\*.*
    - name: Upload ThemeTool to Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ThemeTool
        path: |
          .\bin\Release\Win32\ThemeTool.exe
          .\bin\Release\Win32\ThemeTool.pdb
          
  release:
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ThemeTool
      - name: Get tag version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ThemeTool.exe
          name: Release
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          generate_release_notes: false
          draft: false
          prerelease: false